function init(self)
	gui.set_scale(gui.get_node("hand"), vmath.vector3(1.2, 1.2, 1))
	gui.animate(gui.get_node("hand"), "scale.x", 1, gui.EASING_INQUAD, 0.5, 0, nil, gui.PLAYBACK_LOOP_PINGPONG)
	gui.animate(gui.get_node("hand"), "scale.y", 1, gui.EASING_INQUAD, 0.5, 0, nil, gui.PLAYBACK_LOOP_PINGPONG)
end

function final(self)
end

function update(self, dt)
end

function on_message(self, message_id, message, sender)
end

function on_input(self, action_id, action)
end
